config/routes.rb
Rails.application.routes.draw do

  resources :movies
  resources :crawlers, only: [:new, :create]

end

app/models/movie.rb
class Movie < ActiveRecord::Base

    # link:string
    # name:string
    # size:string
    # files:integer
    # age:string
    # seed:integer
    # leech:integer
    # imdb:real

    before_save :convert_age
    validates :name, presence: true
    validates :link, presence: true

    private

        def convert_age
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/crawlers_controller.rb
require 'open-uri'
class CrawlersController < ApplicationController

  def new
  end

  def create
    new_records = crawl
    flash[:success] = "Movie DB has been updated with #{new_records} new movies."
    redirect_to movies_url
  end

  private

    def human_size_to_bytes(num)
      @regex = /^([0-9]+\.?[0-9]*?) (.*)/
      @sizes = { 'KB' => 1024, 'MB' => 1024**2, 'GB' => 1024**3}
      m = num.match(@regex)
      return (m[1].to_f * @sizes[m[2]]).to_i
    end

    def crawl
        records = 0
        for page in 1..2
            records += retrieve(page)
        end
        return records
    end

    def retrieve(page)
        logger.debug "retrieving page #{page}"

        site = "http://kat.cr/movies/#{page}/?field=seeders&sorder=desc"
        local_dir = 'data_hold'
        local_fname = "#{local_dir}/#{page}.html"

        FileUtils.makedirs(local_dir) unless File.exists?local_dir

        if File.exists?(local_fname)
            logger.debug "Reading local #{local_fname}"
            page = Nokogiri::HTML(open(local_fname))
        else
            logger.debug "Fetching #{site}"
            page = Nokogiri::HTML(open(site))
            File.open(local_fname, "w") { |f| f.write(page.to_html)}
        end

        odd = extract_records(page.css("tr.odd"))
        even = extract_records(page.css("tr.even"))
        logger.debug "retrieved #{odd+even} records"

        return odd+even
    end

    def extract_records(records)
        base = "http://kat.cr"
        new_records = 0
        records.each do |r|
            logger.debug "processing #{new_records}th records "
            maincell = r.css("a.cellMainLink")[0]

            begin
              m = Movie.new(link: base + maincell["href"],
                            name: maincell.text,
                            size:  human_size_to_bytes(r.css("td")[1].text),
                            files: r.css("td")[2].text,
                            age:   r.css("td")[3].text,
                            seed:  r.css("td")[4].text,
                            leech: r.css("td")[5].text,
                            imdb: 0)
              new_records += 1 if m.save
            rescue ActiveRecord::RecordNotUnique
              logger.debug "(#{maincell.text}) already exists"
            end
        end
        logger.debug "#{new_records} new records"

        return new_records
    end



end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.paginate(per_page: 20, page: params[:page])
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:category, :link, :name, :size, :files, :age, :seed, :leech, :imdb, :direction)
    end

    def sort_column
      Movie.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crawlers_helper.rb
module CrawlersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/crawlers/create.html.erb
<h1>Crawlers#create</h1>
<p>Find me in app/views/crawlers/create.html.erb</p>

app/views/crawlers/new.html.erb
<% provide(:title, 'Crawling KAT') %>
<h1>Crawling KAT</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(:crawler, url: crawlers_path) do |f| %>
            <%= f.submit "Crawl KAT", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>

    <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :files %><br>
    <%= f.number_field :files %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :seed %><br>
    <%= f.number_field :seed %>
  </div>
  <div class="field">
    <%= f.label :leech %><br>
    <%= f.number_field :leech %>
  </div>
  <div class="field">
    <%= f.label :imdb %><br>
    <%= f.text_field :imdb %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>KAT Movies</h1>

<table>
  <thead>
    <tr>
      <th>name</th>
      <th>size</th>
      <th>Files</th>
      <th>age</th>
      <th>seed</th>
      <th>leech</th>
      <th>imdb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.name, movie.link %></td>
        <td><%= number_to_human_size(movie.size) %></td>
        <td><%= movie.files %></td>
        <td><%= movie.age %></td>
        <td><%= movie.seed %></td>
        <td><%= movie.leech %></td>
        <td><%= movie.imdb || 0 %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @movies %>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @movie.category %>
</p>

<p>
  <strong>Link:</strong>
  <%= @movie.link %>
</p>

<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @movie.size %>
</p>

<p>
  <strong>Files:</strong>
  <%= @movie.files %>
</p>

<p>
  <strong>Age:</strong>
  <%= @movie.age %>
</p>

<p>
  <strong>Seed:</strong>
  <%= @movie.seed %>
</p>

<p>
  <strong>Leech:</strong>
  <%= @movie.leech %>
</p>

<p>
  <strong>Imdb:</strong>
  <%= @movie.imdb %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>